# data config
data_root: /home/wenqi/Data0/kcl_noncartesian/CINE/data/
# data_root: /u/home/huw/Data0/
# data_root: /data1/kcl/CINE/data/
subjects: [1]
slice: 0
coil_select: [2,3,4,5,6,7] #[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18] #
num_cardiac_cycles: 4
transient_magnetization: 600
batch_size: 30000 #30000
num_workers: 16
sample_per_epoch: 100
random_sample: False
sample_spoke: False
n_spoke: 1500 #1500
n_kpoint_perspoke: 500 #100

# model config for mlp
model: siren
coord_dim: 4
num_layers: 8
feature_dim:  512
out_dim: 1

# train config
num_steps: 50000
lr: 3e-5

# loss config
loss_type: hdr_ff #weighted_l1 #weighted_l1
hdr_eps: 1e-2
hdr_ff_sigma: 1
hdr_ff_factor: 0

# recon config
nt: 30
nx: 256
ny: 256

# experiment summary config
exp_summary: wandb
# wandb config
wandb_entity: wenqihuang
wandb_project: NIK